version: '3.8'

services:
  monitoring-app:
    build: .
    container_name: freedmon-app
    restart: unless-stopped
    volumes:
      - ./freedmon.db:/app/freedmon.db
      - ./snapshots:/app/snapshots
      # Persist crop configuration
      - ./crop_config.json:/app/crop_config.json
    devices:
      - "/dev/video0:/dev/video0"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - USE_MOCK_CAMERA=0
    stdin_open: true
    tty: true
    privileged: true
